version: "3.3"
services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - /libros-db-volume:/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend/
    tty: true
    volumes:
     - /libros-log-volume:/librosLogs
    env_file:
      - ./backend/.env
    environment:
      WAIT_HOSTS: mongo:27017
    command: ["npm", "run", "docker:dev"]
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  frontend:
    build: ./frontend-build/
    tty: true
    command: ["serve", "./", "-l", "80"]
    environment:
      WAIT_HOSTS: backend:3000
    ports:
      - "80:80"
    depends_on:
      - mongo
      - backend
    links:
      - backend
volumes:
  libros-db-volume:
  libros-log-volume:
