export const AUTH_LOGIN_REQUEST = "AuthModule/AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_RECEIVE = "AuthModule/AUTH_LOGIN_RECEIVE";
export const AUTH_LOGIN_FAILED = "AuthModule/AUTH_LOGIN_FAILED";

export const AUTH_LOGOUT_REQUEST = "AuthModule/AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_RECEIVE = "AuthModule/AUTH_LOGOUT_RECEIVE";
export const AUTH_LOGOUT_FAILED = "AuthModule/AUTH_LOGOUT_FAILED";

export const AUTH_REGISTER_REQUEST = "AuthModule/AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_RECEIVE = "AuthModule/AUTH_REGISTER_RECEIVE";
export const AUTH_REGISTER_FAILED = "AuthModule/AUTH_REGISTER_FAILED";

export const AUTH_VERIFY_REQUEST = "AuthModule/AUTH_VERIFY_REQUEST";
