// Fetch
export const PUBLISHERS_FETCH_REQUEST =
  "PublishersModule/PUBLISHERS_FETCH_REQUEST";

export const PUBLISHERS_FETCH_RECEIVE =
  "PublishersModule/PUBLISHERS_FETCH_RECEIVE";

export const PUBLISHERS_FETCH_FAILED =
  "PublishersModule/PUBLISHERS_FETCH_FAILED";

// Create
export const PUBLISHER_CREATE_REQUEST =
  "PublishersModule/PUBLISHER_CREATE_REQUEST";

export const PUBLISHER_CREATE_RECEIVE =
  "PublishersModule/PUBLISHER_CREATE_RECEIVE";

export const PUBLISHER_CREATE_FAILED =
  "PublishersModule/PUBLISHER_CREATE_FAILED";

// Remove
export const PUBLISHER_REMOVE_REQUEST =
  "PublishersModule/PUBLISHER_REMOVE_REQUEST";

export const PUBLISHER_REMOVE_RECEIVE =
  "PublishersModule/PUBLISHER_REMOVE_RECEIVE";

export const PUBLISHER_REMOVE_FAILED =
  "PublishersModule/PUBLISHER_REMOVE_FAILED";
