export const USER_LOANS_REQUEST = "UserModule/USER_LOANS_REQUEST";
export const USER_LOANS_RECEIVE = "UserModule/USER_LOANS_RECEIVE";
export const USER_LOANS_FAILED = "UserModule/USER_LOANS_FAILED";

export const USERS_FETCH_REQUEST = "UserModule/USERS_FETCH_REQUEST";
export const USERS_FETCH_RECEIVE = "UserModule/USERS_FETCH_RECEIVE";
export const USERS_FETCH_FAILED = "UserModule/USERS_FETCH_FAILED";

export const USER_FETCH_REQUEST = "UserModule/USER_FETCH_REQUEST";
export const USER_FETCH_RECEIVE = "UserModule/USER_FETCH_RECEIVE";
export const USER_FETCH_FAILED = "UserModule/USER_FETCH_FAILED";
